version: "3.3"

services:
  db:
    image: postgres:14.0
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
  processing_module:
    build: processing_module/
    hostname: rundeck
    ports:
      - 4440:4440
    volumes:
      - ./data/shared_data:/shared/data
      - ./processing_module/scripts:/scripts
      - ./processing_module/rundeck:/etc/rundeck
    environment:
      RUNDECK_TOKENS_FILE: /etc/rundeck/tokens.properties
  configure_rundeck:
    image: curlimages/curl:7.79.1
    restart: "no"
    depends_on:
      - processing_module
    volumes:
      - ./processing_module/rundeck:/etc/rundeck
    entrypoint: ["sh", "/etc/rundeck/init.sh"]
  gui:
    build: gui/
    hostname: gui
    ports:
      - 5000:5000
    depends_on:
      - db
